### ISSUE TITLE
TypeError: n.replace is not a function

### ISSUE THREAD

**Issue by nathkrill** [bigbitecreative/macy.js#39] opened 2018-03-20 17:28 UTC
I am using Macy (the latest version from npm - 2.3.0) and upon initialisation I get the error: `Uncaught TypeError: n.replace is not a function`.

Here is how I am using Macy:
```
var masonry = (function () {
    'use strict';

    var feed,
        macy;

    function reinit() {
        macy.recalculate();
    }

    function init() {
        feed = document.querySelector('.feed');

        if (!feed) {
            return;
        }

        macy = Macy({
            container: feed,
            columns: 1,
            waitForImages: true,
            mobileFirst: true,
            breakAt: {
                768: 3
            }
        });

        window.resize = reinit;
    }

    document.addEventListener('DOMContentLoaded', init);

    return {
        init: init,
        reinit: reinit
    }

}());
```
The idea is that I can call `masonry.reinit` any time I need to reinitialise and it will recalculate.

**Comment by nathkrill** [comment] 2018-03-20 17:56
Saw my problem - I was passing a variable into `container` rather than an element selector. Perhaps this would make a nice feature?

**Comment by jrmd** [comment] 2018-04-12 11:08
hey @nathkrill 

I will look to implement this when i have some free time as i believe it would be handy :) 

Closing for now as its not a bug :)

**Closed by jrmd** 2018-04-12 11:08 UTC
