### ISSUE TITLE
TypeError: (intermediate value).querySelectorAll is not a function

### ISSUE THREAD

**Issue by daybugging** [bigbitecreative/macy.js#38] opened 2018-02-12 12:07 UTC
Any ideas on that? Using latest version available through NPM.
Thx!

**Comment by jrmd** [comment] 2018-03-20 17:30
hey @daybugging 

Could you provide an example on how you are using macy, so i can reproduce?

Thanks,
Jerome

**Comment by jrmd** [comment] 2018-04-12 11:16
Closing as no information has been provided.

**Closed by jrmd** 2018-04-12 11:16 UTC

**Comment by ashfahan** [comment] 2019-02-22 23:16
This issue still exist 
its odd that the error shows up only at $react-scripts test --env=jsdom 

here is the log

`PS J:\Web Sites\ashfahan-portfolio-app> yarn test
yarn run v1.12.1
$ react-scripts test --env=jsdom

 RUNS  src/Main.test.jsx

Test Suites: 0 of 1 total
Tests:       0 total
Snapshots:   0 total
  console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
    Error: Uncaught [TypeError: (n || document).querySelectorAll is not a function]
        at reportException (J:\Web Sites\ashfahan-portfolio-app\node_modules\jsdom\lib\jsdom\living\helpers\runtime-script-errors.js:66:24)
        at invokeEventListeners (J:\Web Sites\ashfahan-portfolio-app\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:209:9)
        at HTMLUnknownElementImpl._dispatch (J:\Web Sites\ashfahan-portfolio-app\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:119:9)
        at HTMLUnknownElementImpl.dispatchEvent (J:\Web Sites\ashfahan-portfolio-app\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:82:17)
        at HTMLUnknownElementImpl.dispatchEvent (J:\Web Sites\ashfahan-portfolio-app\node_modules\jsdom\lib\jsdom\living\nodes\HTMLElement-impl.js:30:27)
        at HTMLUnknownElement.dispatchEvent (J:\Web Sites\ashfahan-portfolio-app\node_modules\jsdom\lib\jsdom\living\generated\EventTarget.js:157:21)
        at Object.invokeGuardedCallbackDev (J:\Web Sites\ashfahan-portfolio-app\node_modules\react-dom\cjs\react-dom.development.js:199:16)
        at invokeGuardedCallback (J:\Web Sites\ashfahan-portfolio-app\node_modules\react-dom\cjs\react-dom.development.js:256:31)
        at commitRoot (J:\Web Sites\ashfahan-portfolio-app\node_modules\react-dom\cjs\react-dom.development.js:18744:7)
        at J:\Web Sites\ashfahan-portfolio-app\node_modules\react-dom\cjs\react-dom.development.js:20214:5 TypeError: (n || document).querySelectorAll is not a function
        at t.f.byCss (J:\Web Sites\ashfahan-portfolio-app\node_modules\macy\dist\macy.js:117:26)
        at new t (J:\Web Sites\ashfahan-portfolio-app\node_modules\macy\dist\macy.js:112:73)
        at t (J:\Web Sites\ashfahan-portfolio-app\node_modules\macy\dist\macy.js:111:36)
        at _ (J:\Web Sites\ashfahan-portfolio-app\node_modules\macy\dist\macy.js:229:12)
        at b (J:\Web Sites\ashfahan-portfolio-app\node_modules\macy\dist\macy.js:241:16)
        at new t (J:\Web Sites\ashfahan-portfolio-app\node_modules\macy\dist\macy.js:330:47)
        at SkillSection.componentDidMount (J:\Web Sites\ashfahan-portfolio-app\src\pages\SkillSection.jsx:18:16)
        at commitLifeCycles (J:\Web Sites\ashfahan-portfolio-app\node_modules\react-dom\cjs\react-dom.development.js:17130:22)
        at commitAllLifeCycles (J:\Web Sites\ashfahan-portfolio-app\node_modules\react-dom\cjs\react-dom.development.js:18532:7)
        at HTMLUnknownElement.callCallback (J:\Web Sites\ashfahan-portfolio-app\node_modules\react-dom\cjs\react-dom.development.js:149:14)
        at invokeEventListeners (J:\Web Sites\ashfahan-portfolio-app\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:193:27)
        at HTMLUnknownElementImpl._dispatch (J:\Web Sites\ashfahan-portfolio-app\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:119:9)
        at HTMLUnknownElementImpl.dispatchEvent (J:\Web Sites\ashfahan-portfolio-app\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:82:17)
        at HTMLUnknownElementImpl.dispatchEvent (J:\Web Sites\ashfahan-portfolio-app\node_modules\jsdom\lib\jsdom\living\nodes\HTMLElement-impl.js:30:27)
        at HTMLUnknownElement.dispatchEvent (J:\Web Sites\ashfahan-portfolio-app\node_modules\jsdom\lib\jsdom\living\generated\EventTarget.js:157:21)
        at Object.invokeGuardedCallbackDev (J:\Web Sites\ashfahan-portfolio-app\node_modules\react-dom\cjs\react-dom.development.js:199:16)
        at invokeGuardedCallback (J:\Web Sites\ashfahan-portfolio-app\node_modules\react-dom\cjs\react-dom.development.js:256:31)
        at commitRoot (J:\Web Sites\ashfahan-portfolio-app\node_modules\react-dom\cjs\react-dom.development.js:18744:7)
        at J:\Web Sites\ashfahan-portfolio-app\node_modules\react-dom\cjs\react-dom.development.js:20214:5
        at Object.unstable_runWithPriority (J:\Web Sites\ashfahan-portfolio-app\node_modules\scheduler\cjs\scheduler.development.js:255:12)
        at completeRoot (J:\Web Sites\ashfahan-portfolio-app\node_modules\react-dom\cjs\react-dom.development.js:20213:13)
        at performWorkOnRoot (J:\Web Sites\ashfahan-portfolio-app\node_modules\react-dom\cjs\react-dom.development.js:20142:9)
        at performWork (J:\Web Sites\ashfahan-portfolio-app\node_modules\react-dom\cjs\react-dom.development.js:20050:7)
        at performSyncWork (J:\Web Sites\ashfahan-portfolio-app\node_modules\react-dom\cjs\react-dom.development.js:20024:3)
        at requestWork (J:\Web Sites\ashfahan-portfolio-app\node_modules\react-dom\cjs\react-dom.development.js:19893:5)
        at scheduleWork (J:\Web Sites\ashfahan-portfolio-app\node_modules\react-dom\cjs\react-dom.development.js:19707:5)
        at scheduleRootUpdate (J:\Web Sites\ashfahan-portfolio-app\node_modules\react-dom\cjs\react-dom.development.js:20368:3)
        at updateContainerAtExpirationTime (J:\Web Sites\ashfahan-portfolio-app\node_modules\react-dom\cjs\react-dom.development.js:20396:10)
        at updateContainer (J:\Web Sites\ashfahan-portfolio-app\node_modules\react-dom\cjs\react-dom.development.js:20453:10)
        at ReactRoot.Object.<anonymous>.ReactRoot.render (J:\Web Sites\ashfahan-portfolio-app\node_modules\react-dom\cjs\react-dom.development.js:20749:3)
        at J:\Web Sites\ashfahan-portfolio-app\node_modules\react-dom\cjs\react-dom.development.js:20886:14
        at unbatchedUpdates (J:\Web Sites\ashfahan-portfolio-app\node_modules\react-dom\cjs\react-dom.development.js:20255:10)
        at legacyRenderSubtreeIntoContainer (J:\Web Sites\ashfahan-portfolio-app\node_modules\react-dom\cjs\react-dom.development.js:20882:5)
        at Object.render (J:\Web Sites\ashfahan-portfolio-app\node_modules\react-dom\cjs\react-dom.development.js:20951:12)
        at Object.render (J:\Web Sites\ashfahan-portfolio-app\src\Main.test.jsx:7:12)
        at Object.asyncJestTest (J:\Web Sites\ashfahan-portfolio-app\node_modules\jest-jasmine2\build\jasmine_async.js:108:37)
        at resolve (J:\Web Sites\ashfahan-portfolio-app\node_modules\jest-jasmine2\build\queue_runner.js:56:12)
        at new Promise (<anonymous>)
        at mapper (J:\Web Sites\ashfahan-portfolio-app\node_modules\jest-jasmine2\build\queue_runner.js:43:19)
        at promise.then (J:\Web Sites\ashfahan-portfolio-app\node_modules\jest-jasmine2\build\queue_runner.js:87:41)
        at process.internalTickCallback (internal/process/next_tick.js:77:7)

  console.error node_modules/react-dom/cjs/react-dom.development.js:16913
    The above error occurred in the <SkillSection> component:
        in SkillSection (at Home.jsx:47)
        in section (at Home.jsx:45)
        in Home (created by Context.Consumer)
        in Connect(Home) (at Main.jsx:35)
        in div (created by Basic)
        in Basic (created by Context.Consumer)
        in Adapter (at Main.jsx:34)
        in div (created by BasicLayout)
        in BasicLayout (created by Context.Consumer)
        in Adapter (at Main.jsx:32)
 FAIL  src/Main.test.jsxMain.jsx:31)
  × renders without crashing (309ms)

  ● renders without crashing

    TypeError: (n || document).querySelectorAll is not a function

      16 | export default class SkillSection extends Component {
      17 |      componentDidMount() {
    > 18 |              this.Cards = new Macy({
         |                           ^
      19 |                      container: "#Skills_macy",
      20 |                      mobileFirst: true,
      21 |                      columns: 3,

      at t.f.byCss (node_modules/macy/dist/macy.js:117:26)
      at new t (node_modules/macy/dist/macy.js:112:73)
      at t (node_modules/macy/dist/macy.js:111:36)
      at _ (node_modules/macy/dist/macy.js:229:12)
      at b (node_modules/macy/dist/macy.js:241:16)
      at new t (node_modules/macy/dist/macy.js:330:47)
      at SkillSection.componentDidMount (src/pages/SkillSection.jsx:18:16)
      at commitLifeCycles (node_modules/react-dom/cjs/react-dom.development.js:17130:22)
      at commitAllLifeCycles (node_modules/react-dom/cjs/react-dom.development.js:18532:7)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:149:14)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:199:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:256:31)
      at commitRoot (node_modules/react-dom/cjs/react-dom.development.js:18744:7)
      at node_modules/react-dom/cjs/react-dom.development.js:20214:5
      at Object.unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:255:12)
      at completeRoot (node_modules/react-dom/cjs/react-dom.development.js:20213:13)
      at performWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:20142:9)
      at performWork (node_modules/react-dom/cjs/react-dom.development.js:20050:7)
      at performSyncWork (node_modules/react-dom/cjs/react-dom.development.js:20024:3)
      at requestWork (node_modules/react-dom/cjs/react-dom.development.js:19893:5)
      at scheduleWork (node_modules/react-dom/cjs/react-dom.development.js:19707:5)
      at scheduleRootUpdate (node_modules/react-dom/cjs/react-dom.development.js:20368:3)
      at updateContainerAtExpirationTime (node_modules/react-dom/cjs/react-dom.development.js:20396:10)
      at updateContainer (node_modules/react-dom/cjs/react-dom.development.js:20453:10)
      at ReactRoot.Object.<anonymous>.ReactRoot.render (node_modules/react-dom/cjs/react-dom.development.js:20749:3)
      at node_modules/react-dom/cjs/react-dom.development.js:20886:14
      at unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:20255:10)
      at legacyRenderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:20882:5)
      at Object.render (node_modules/react-dom/cjs/react-dom.development.js:20951:12)
      at Object.render (src/Main.test.jsx:7:12)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        5.763s
Ran all test suites related to changed files.`

after i replaced `return (n || document).querySelectorAll(t);` with 		return document.querySelectorAll(t);

the problem seems to be fixed.

**Comment by ashfahan** [comment] 2019-02-23 11:30
Hi @jrmd 

This issue still exist in latest NPM version of macy
its odd that the error shows up only at $react-scripts test --env=jsdom 

here is the log

    J:\Web Sites\project> yarn test
    yarn run v1.12.1
    $ react-scripts test --env=jsdom
    
     RUNS  src/Main.test.jsx

    Test Suites: 0 of 1 total
    Tests:       0 total
    Snapshots:   0 total
      console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
        Error: Uncaught [TypeError: (n || document).querySelectorAll is not a function]
            at reportException (J:\Web Sites\project\node_modules\jsdom\lib\jsdom\living\helpers\runtime-script-errors.js:66:24)
            at invokeEventListeners (J:\Web Sites\project\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:209:9)
            at HTMLUnknownElementImpl._dispatch (J:\Web Sites\project\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:119:9)
            at HTMLUnknownElementImpl.dispatchEvent (J:\Web Sites\project\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:82:17)
            at HTMLUnknownElementImpl.dispatchEvent (J:\Web Sites\project\node_modules\jsdom\lib\jsdom\living\nodes\HTMLElement-impl.js:30:27)
            at HTMLUnknownElement.dispatchEvent (J:\Web Sites\project\node_modules\jsdom\lib\jsdom\living\generated\EventTarget.js:157:21)
            at Object.invokeGuardedCallbackDev (J:\Web Sites\project\node_modules\react-dom\cjs\react-dom.development.js:199:16)
            at invokeGuardedCallback (J:\Web Sites\project\node_modules\react-dom\cjs\react-dom.development.js:256:31)
            at commitRoot (J:\Web Sites\project\node_modules\react-dom\cjs\react-dom.development.js:18744:7)
            at J:\Web Sites\project\node_modules\react-dom\cjs\react-dom.development.js:20214:5 TypeError: (n || document).querySelectorAll is not a function
            at t.f.byCss (J:\Web Sites\project\node_modules\macy\dist\macy.js:117:26)
            at new t (J:\Web Sites\project\node_modules\macy\dist\macy.js:112:73)
            at t (J:\Web Sites\project\node_modules\macy\dist\macy.js:111:36)
            at _ (J:\Web Sites\project\node_modules\macy\dist\macy.js:229:12)
            at b (J:\Web Sites\project\node_modules\macy\dist\macy.js:241:16)
            at new t (J:\Web Sites\project\node_modules\macy\dist\macy.js:330:47)
            at SkillSection.componentDidMount (J:\Web Sites\project\src\pages\SkillSection.jsx:18:16)
            at commitLifeCycles (J:\Web Sites\project\node_modules\react-dom\cjs\react-dom.development.js:17130:22)
            at commitAllLifeCycles (J:\Web Sites\project\node_modules\react-dom\cjs\react-dom.development.js:18532:7)
            at HTMLUnknownElement.callCallback (J:\Web Sites\project\node_modules\react-dom\cjs\react-dom.development.js:149:14)
            at invokeEventListeners (J:\Web Sites\project\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:193:27)
            at HTMLUnknownElementImpl._dispatch (J:\Web Sites\project\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:119:9)
            at HTMLUnknownElementImpl.dispatchEvent (J:\Web Sites\project\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:82:17)
            at HTMLUnknownElementImpl.dispatchEvent (J:\Web Sites\project\node_modules\jsdom\lib\jsdom\living\nodes\HTMLElement-impl.js:30:27)
            at HTMLUnknownElement.dispatchEvent (J:\Web Sites\project\node_modules\jsdom\lib\jsdom\living\generated\EventTarget.js:157:21)
            at Object.invokeGuardedCallbackDev (J:\Web Sites\project\node_modules\react-dom\cjs\react-dom.development.js:199:16)
            at invokeGuardedCallback (J:\Web Sites\project\node_modules\react-dom\cjs\react-dom.development.js:256:31)
            at commitRoot (J:\Web Sites\project\node_modules\react-dom\cjs\react-dom.development.js:18744:7)
            at J:\Web Sites\project\node_modules\react-dom\cjs\react-dom.development.js:20214:5
            at Object.unstable_runWithPriority (J:\Web Sites\project\node_modules\scheduler\cjs\scheduler.development.js:255:12)
            at completeRoot (J:\Web Sites\project\node_modules\react-dom\cjs\react-dom.development.js:20213:13)
            at performWorkOnRoot (J:\Web Sites\project\node_modules\react-dom\cjs\react-dom.development.js:20142:9)
            at performWork (J:\Web Sites\project\node_modules\react-dom\cjs\react-dom.development.js:20050:7)
            at performSyncWork (J:\Web Sites\project\node_modules\react-dom\cjs\react-dom.development.js:20024:3)
            at requestWork (J:\Web Sites\project\node_modules\react-dom\cjs\react-dom.development.js:19893:5)
            at scheduleWork (J:\Web Sites\project\node_modules\react-dom\cjs\react-dom.development.js:19707:5)
            at scheduleRootUpdate (J:\Web Sites\project\node_modules\react-dom\cjs\react-dom.development.js:20368:3)
            at updateContainerAtExpirationTime (J:\Web Sites\project\node_modules\react-dom\cjs\react-dom.development.js:20396:10)
            at updateContainer (J:\Web Sites\project\node_modules\react-dom\cjs\react-dom.development.js:20453:10)
            at ReactRoot.Object.<anonymous>.ReactRoot.render (J:\Web Sites\project\node_modules\react-dom\cjs\react-dom.development.js:20749:3)
            at J:\Web Sites\project\node_modules\react-dom\cjs\react-dom.development.js:20886:14
            at unbatchedUpdates (J:\Web Sites\project\node_modules\react-dom\cjs\react-dom.development.js:20255:10)
            at legacyRenderSubtreeIntoContainer (J:\Web Sites\project\node_modules\react-dom\cjs\react-dom.development.js:20882:5)
            at Object.render (J:\Web Sites\project\node_modules\react-dom\cjs\react-dom.development.js:20951:12)
            at Object.render (J:\Web Sites\project\src\Main.test.jsx:7:12)
            at Object.asyncJestTest (J:\Web Sites\project\node_modules\jest-jasmine2\build\jasmine_async.js:108:37)
            at resolve (J:\Web Sites\project\node_modules\jest-jasmine2\build\queue_runner.js:56:12)
            at new Promise (<anonymous>)
            at mapper (J:\Web Sites\project\node_modules\jest-jasmine2\build\queue_runner.js:43:19)
            at promise.then (J:\Web Sites\project\node_modules\jest-jasmine2\build\queue_runner.js:87:41)
            at process.internalTickCallback (internal/process/next_tick.js:77:7)
    
      console.error node_modules/react-dom/cjs/react-dom.development.js:16913
        The above error occurred in the <SkillSection> component:
            in SkillSection (at Home.jsx:47)
            in section (at Home.jsx:45)
            in Home (created by Context.Consumer)
            in Connect(Home) (at Main.jsx:35)
            in div (created by Basic)
            in Basic (created by Context.Consumer)
            in Adapter (at Main.jsx:34)
            in div (created by BasicLayout)
            in BasicLayout (created by Context.Consumer)
            in Adapter (at Main.jsx:32)
     FAIL  src/Main.test.jsxMain.jsx:31)
      × renders without crashing (309ms)

    TypeError: (n || document).querySelectorAll is not a function

      16 | export default class SkillSection extends Component {
      17 |      componentDidMount() {
    > 18 |              this.Cards = new Macy({
         |                           ^
      19 |                      container: "#Skills_macy",
      20 |                      mobileFirst: true,
      21 |                      columns: 3,

      at t.f.byCss (node_modules/macy/dist/macy.js:117:26)
      at new t (node_modules/macy/dist/macy.js:112:73)
      at t (node_modules/macy/dist/macy.js:111:36)
      at _ (node_modules/macy/dist/macy.js:229:12)
      at b (node_modules/macy/dist/macy.js:241:16)
      at new t (node_modules/macy/dist/macy.js:330:47)
      at SkillSection.componentDidMount (src/pages/SkillSection.jsx:18:16)
      at commitLifeCycles (node_modules/react-dom/cjs/react-dom.development.js:17130:22)
      at commitAllLifeCycles (node_modules/react-dom/cjs/react-dom.development.js:18532:7)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:149:14)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:199:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:256:31)
      at commitRoot (node_modules/react-dom/cjs/react-dom.development.js:18744:7)
      at node_modules/react-dom/cjs/react-dom.development.js:20214:5
      at Object.unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:255:12)
      at completeRoot (node_modules/react-dom/cjs/react-dom.development.js:20213:13)
      at performWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:20142:9)
      at performWork (node_modules/react-dom/cjs/react-dom.development.js:20050:7)
      at performSyncWork (node_modules/react-dom/cjs/react-dom.development.js:20024:3)
      at requestWork (node_modules/react-dom/cjs/react-dom.development.js:19893:5)
      at scheduleWork (node_modules/react-dom/cjs/react-dom.development.js:19707:5)
      at scheduleRootUpdate (node_modules/react-dom/cjs/react-dom.development.js:20368:3)
      at updateContainerAtExpirationTime (node_modules/react-dom/cjs/react-dom.development.js:20396:10)
      at updateContainer (node_modules/react-dom/cjs/react-dom.development.js:20453:10)
      at ReactRoot.Object.<anonymous>.ReactRoot.render (node_modules/react-dom/cjs/react-dom.development.js:20749:3)
      at node_modules/react-dom/cjs/react-dom.development.js:20886:14
      at unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:20255:10)
      at legacyRenderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:20882:5)
      at Object.render (node_modules/react-dom/cjs/react-dom.development.js:20951:12)
      at Object.render (src/Main.test.jsx:7:12)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        5.763s
Ran all test suites related to changed files.

after i replaced `return (n || document).querySelectorAll(t);` with 		return document.querySelectorAll(t);

the problem seems to be fixed.

**Comment by ma-vo** [comment] 2021-03-10 10:52
still existing. please reopen.

**Comment by jrmd** [comment] 2021-03-10 10:56
@ma-vo could you provide  an example of how you are using this to get an error please?
